/**
 * Basic serial implementation for attiny85
 */

#include <avr/io.h>
#include <util/delay.h>

/**
 * Datasheet refers to SDA and SCL for serial communication
 * Map those here so I can use them in other operations
 */
#define SDA PB0
#define SCL PB2

static uint32_t s_baud_rate = 9600;

/**
 * For controlling serial clock
 * This essentially sends the bit out from the data register
 */
static inline void Serial_StrobeClock(void)
{
    /**
     * Datasheet says writing to the serial control
     * register will strobe clock...
     *
     * Also says: The clock is generated by the master by toggling the USCK
     * pin via the PORTB register.
     * So not sure if ths should be PORTB or USICLK
     */
    USICR |= GEN_BIT(USICLK);
}

/**
 * Perform operations needed to begin serial transfer
 */
static inline void Serial_BeginTransfer(void)
{
    /**
     * The start condition is generated by the master by forcing the SDA
     * low line while keeping the SCL line high (A).
     */
    // SDA is output, write it low.
    PORTB &= ~(GEN_BIT(SDA));
    // SCL is input, set to 1 to hold high via pull-up resistor.
    PORTB |= GEN_BIT(SCL);
    // Allow output to detect start condition?
    _delay_us(1);
}

static void Serial_ExecuteByteTransfer(char byte)
{
    // Put byte in data register
    USIDR = byte;
    // release SCL to slave
    PORTB &= ~(GEN_BIT(SCL));

}
Serial_WaitForTransferComplete();

/**
 * Initialize serial interface for 2-wire mode
 */
void Serial_Initialize(void)
{
    // Initialize to 2-wire mode
    // Initial value for USICR register is all 0's
    // 2-wire mode requires USIWM1 = 1 and USIWM0 = 0
    // Clear current wire mode value
    USICR &= ~(GEN_BIT(USIWM0) | GEN_BIT(USIWM1));
    // Write bit 1 to setup 2-wire mode.
    USICR |= GEN_BIT(USIWM1);

    // Set SDA to output
    DDRB |= GEN_BIT(SDA) | GEN_BIT(SCL);
}

/**
 * Set baud rate for serial transfer
 * TODO: This could probably be an input for Serial_Initialize
 */
void Serial_SetBaudRate(uint32_t baud_rate)
{

}

/**
 * Send string over serial
 *
 * @param[in] string - must be null terminated
 */
void Serial_Write(char *string)
{
    uint32_t string_index = 0;

    Serial_BeginTransfer();
    while (string[string_index] != '\0')
    {
        Serial_ExecuteByteTransfer(string[string_index]);
        Serial_WaitForTransferComplete();
    }
}
